### ISSUE TITLE
docs for pre-genesis instructions messed up

### ISSUE THREAD

**Issue by gavinly** [heliaxdev/mainnet-genesis-test#1]
https://docs.namada.net/networks/starting-network/genesis-flow/participants

idk if it's the link or the docs, but i can't see the instructions. this what i see:
<img width="1050" alt="image" src="https://github.com/user-attachments/assets/6e172c1a-85de-4f55-a94f-7ffa4d53ad21">

**Comment by Fraccaman** [comment]
fixed
